# pipesplit — virtual audio sinks
# Install: ~/.config/pipewire/pipewire.conf.d/pipesplit.conf

context.objects = [
    {
        factory = adapter
        args = {
            factory.name   = support.null-audio-sink
            node.name       = games
            node.description = "Games"
            media.class     = Audio/Sink
            audio.position  = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
        }
    }
    {
        factory = adapter
        args = {
            factory.name   = support.null-audio-sink
            node.name       = music
            node.description = "Music"
            media.class     = Audio/Sink
            audio.position  = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
        }
    }
    {
        factory = adapter
        args = {
            factory.name   = support.null-audio-sink
            node.name       = stream-games
            node.description = "Stream-Games"
            media.class     = Audio/Sink
            audio.position  = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
        }
    }
    {
        factory = adapter
        args = {
            factory.name   = support.null-audio-sink
            node.name       = stream-music
            node.description = "Stream-Music"
            media.class     = Audio/Sink
            audio.position  = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
        }
    }
]
